apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroton
spec:
  selector:
    matchLabels:
      app: kroton
  template:
    metadata:
      labels:
        app: kroton
    spec:
      containers:
        - name: kroton
          image: 661984127532.dkr.ecr.us-east-1.amazonaws.com/kroton:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kroton
spec:
  selector:
    app: kroton
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer