apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroton-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kroton
  template:
    metadata:
      labels:
        app: kroton
    spec:
      containers:
        - name: kroton
          image: 661984127532.dkr.ecr.us-east-1.amazonaws.com/kroton:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred

